### ISSUE TITLE
Android compiler error if plugin is added to cordova app

### ISSUE THREAD

**Issue by paulsonnentag** [hirtenfelder/cordova-plugin-template#1]
I have added the plugin as it is to an empty default cordova project and I get the following error when compiling:

```
-pre-compile:
     [echo] Set jars path to: /home/paul/Downloads/test/platforms/android/CordovaLib/ant-build/classes.jar

-compile:
    [javac] Compiling 4 source files to /home/paul/Downloads/test/platforms/android/ant-build/classes
    [javac] /home/paul/Downloads/test/platforms/android/src/cordova/plugin/Template.java:1: error: illegal character: \65279
    [javac] ﻿package cordova.plugin;
    [javac] ^
    [javac] /home/paul/Downloads/test/platforms/android/src/cordova/plugin/Template.java:1: error: class, interface, or enum expected
    [javac] ﻿package cordova.plugin;
    [javac]          ^
    [javac] 2 errors

BUILD FAILED
/home/paul/Android/Sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/paul/Android/Sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 3 seconds

/home/paul/Downloads/test/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/home/paul/Downloads/test/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /home/paul/Downloads/test/platforms/android/cordova/run: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/src/superspawn.js:112:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

**Comment by hirtenfelder** [comment]
Hello

That's a problem related to Byte Order Mark character. Please see http://stackoverflow.com/questions/23211589/error1-1illegalcharacter-ufeff-when-compiling-on-android-studio

I will fix this asap. In the meantime please open the Template.java with Notepad++ (or your Linux file Editor), change encoding to "UTF-8 without BOM" and save it. Then it will compile ..
